sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t diogoxcorreia/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true diogoxcorreia/docker-react npm run test